import { useEffect, useRef, useState } from 'react';
import { getJson, saveInspection } from './api.js';

const checklist = ['tools','jack','spare_tire','radio','carpet','rubber'];
export default function InspectionModal({ open, form, jobId, onClose }) {
  const canvas = useRef(null); const [fuel,setFuel]=useState(50); const [mileage,setMileage]=useState(''); const [notes,setNotes]=useState(''); const [marks,setMarks]=useState({}); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  useEffect(()=>{if(!open)return;getJson(`/inspection/${jobId||'JOB-'+Date.now()}`).then(r=>{const d=r?.data||r;if(d?.fuel_level)setFuel(d.fuel_level);if(d?.current_mileage)setMileage(d.current_mileage);if(d?.notes)setNotes(d.notes);}).catch(()=>{});},[open,jobId]);
  function mark(e){const c=canvas.current;if(!c)return;const r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,ctx=c.getContext('2d');ctx.strokeStyle='#e53935';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,14,0,Math.PI*2);ctx.stroke();}
  async function save(){setSaving(true);try{await saveInspection({job_id:jobId||`JOB-${Date.now()}`,car_plate:form.car_plate,branch_name:form.branch_name,fuel_level:fuel,current_mileage:mileage,inventory_checklist:marks,car_diagram_image:canvas.current?.toDataURL('image/png')||'',notes});setMessage('บันทึกใบตรวจสภาพเรียบร้อยแล้ว');}catch(e){setMessage(e.message);}finally{setSaving(false);}}
  if(!open)return null;
  return <div className="modal-backdrop" role="dialog" aria-modal="true" data-testid="inspection-modal"><div className="inspection-modal"><div className="modal-header"><h2>ใบตรวจสภาพรถ</h2><button onClick={onClose}>×</button></div><div className="inspection-meta"><label>ทะเบียนรถ<input value={form.car_plate||''} readOnly/></label><label>ลูกค้า<input value={form.customer_name||''} readOnly/></label><label>VIN<input value={form.vin_no||''} readOnly/></label><label>เลขเคลม<input value={form.claim_no||''} readOnly/></label></div><div className="inspection-grid"><section><h3>รายการตรวจเช็คภายในรถ</h3>{checklist.map(k=><label className="check-row" key={k}><input type="checkbox" checked={!!marks[k]} onChange={e=>setMarks(x=>({...x,[k]:e.target.checked}))}/>{k.replace('_',' ')}</label>)}<label className="job-field">ระดับน้ำมัน (%)<input type="range" min="0" max="100" value={fuel} onChange={e=>setFuel(e.target.value)}/><span>{fuel}%</span></label><label className="job-field">เลขไมล์<input type="number" value={mileage} onChange={e=>setMileage(e.target.value)}/></label></section><section><h3>ทำเครื่องหมายรอยแผล</h3><canvas ref={canvas} width="600" height="240" onClick={mark} className="inspection-canvas"/><p className="muted">คลิกบนภาพเพื่อทำเครื่องหมายรอยแผล</p><label className="job-field">หมายเหตุ<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></section></div>{message&&<div className="job-notice success">{message}</div>}<div className="modal-actions"><button className="cancel-button" onClick={onClose}>ปิด</button><button className="tool-button" onClick={()=>window.print()}>พิมพ์</button><button className="save-button" data-testid="save-inspection" disabled={saving} onClick={save}>{saving?'กำลังบันทึก...':'บันทึกใบตรวจสภาพ'}</button></div></div></div>;
}
