import { useEffect, useMemo, useState } from 'react';
import { getJson } from './api.js';
export default function QuotaCalendarModal({ open, field, form, onPick, onClose }) {
  const [month,setMonth]=useState(new Date()); const [jobs,setJobs]=useState([]); const [quotas,setQuotas]=useState([]); const [selected,setSelected]=useState(null);
  useEffect(()=>{if(open)Promise.all([getJson('/reports'),getJson('/quotas')]).then(([j,q])=>{setJobs(j||[]);setQuotas(q||[]);}).catch(()=>{});},[open]);
  const days=useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),start=new Date(y,m,1).getDay(),total=new Date(y,m+1,0).getDate();const out=Array(start).fill(null);for(let d=1;d<=total;d++)out.push(new Date(y,m,d));return out;},[month]);
  if(!open)return null;
  const dateKey=d=>d.toISOString().slice(0,10); const stats=d=>{const key=dateKey(d);return {arr:jobs.filter(x=>String(x.arrived_date||'').slice(0,10)===key).length,target:jobs.filter(x=>String(x.target_finish_date||'').slice(0,10)===key).length,del:jobs.filter(x=>String(x.delivery_date||'').slice(0,10)===key).length};};
  return <div className="modal-backdrop" role="dialog" data-testid="quota-calendar-modal"><div className="calendar-modal"><div className="modal-header"><h2>ตารางตรวจสอบโควต้า</h2><button onClick={onClose}>×</button></div><div className="calendar-toolbar"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><strong>{month.toLocaleDateString('th-TH',{month:'long',year:'numeric'})}</strong><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><div className="calendar-grid">{['อา','จ','อ','พ','พฤ','ศ','ส'].map(x=><b key={x}>{x}</b>)}{days.map((d,i)=>d?<button key={i} className="calendar-day" onClick={()=>field==='all'?setSelected(d):onPick(dateKey(d))}><strong>{d.getDate()}</strong><small>เข้า {stats(d).arr} · เสร็จ {stats(d).target} · ส่ง {stats(d).del}</small></button>:<span key={i}/>)}</div>{selected&&<div className="date-choice"><p>เลือกวันที่ {dateKey(selected)}</p><button onClick={()=>{onPick(dateKey(selected),'arrived_date');setSelected(null)}}>ใส่ช่องรถเข้าจอดอู่</button><button onClick={()=>{onPick(dateKey(selected),'target_finish_date');setSelected(null)}}>ใส่ช่องกำหนดซ่อมเสร็จ</button><button onClick={()=>{onPick(dateKey(selected),'delivery_date');setSelected(null)}}>ใส่ช่องส่งมอบรถ</button></div>}<small className="muted">โหลดโควต้าแล้ว {quotas.length} รายการ</small></div></div>;
}
