const express = require('express');
const router = express.Router();
const pool = require('../config/db');

router.get('/parts', async (req, res) => { try { const result = await pool.query(`SELECT m.*, l.location, l.safety_stock FROM rizenicpartsmaster m LEFT JOIN rizenic_part_locations l ON m.part_no = l.part_no AND l.branch_name = $1 ORDER BY m.part_name ASC`, [req.query.branch || 'สำนักงานใหญ่']); res.json(result.rows); } catch (e) { res.status(500).json({ error: e.message }); } });
router.get('/parts/check/:part_no', async (req, res) => { try { const result = await pool.query(`SELECT m.*, l.location, l.safety_stock FROM rizenicpartsmaster m LEFT JOIN rizenic_part_locations l ON m.part_no = l.part_no AND l.branch_name = $2 WHERE m.part_no = $1 LIMIT 1`, [req.params.part_no, req.query.branch || 'สำนักงานใหญ่']); res.json(result.rows[0] || null); } catch (e) { res.status(500).json({ error: e.message }); } });
router.post('/parts', async (req, res) => { const client = await pool.connect(); try { const { part_main_no, part_no, part_name, car_model, part_category, unit_price, location, safety_stock, branch_name } = req.body; const branch = branch_name || 'สำนักงานใหญ่'; await client.query('BEGIN'); await client.query(`INSERT INTO rizenicpartsmaster (part_main_no, part_no, part_name, car_model, part_category, unit_price) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (part_no) DO UPDATE SET part_name = $3, car_model = $4, part_category = $5, unit_price = $6;`, [part_main_no || null, part_no, part_name, car_model || null, part_category || 'อะไหล่ทั่วไป', parseFloat(unit_price) || 0.00]); await client.query(`INSERT INTO rizenic_part_locations (part_no, branch_name, location, safety_stock) VALUES ($1, $2, $3, $4) ON CONFLICT (part_no, branch_name) DO UPDATE SET location = $3, safety_stock = $4;`, [part_no, branch, location || null, parseInt(safety_stock) || 0]); await client.query('COMMIT'); res.json({ success: true }); } catch (e) { await client.query('ROLLBACK'); res.status(500).json({ error: e.message }); } finally { client.release(); } });
router.put('/parts/:id', async (req, res) => { const client = await pool.connect(); try { const { part_main_no, part_no, part_name, car_model, part_category, unit_price, location, safety_stock, branch_name } = req.body; const branch = branch_name || 'สำนักงานใหญ่'; await client.query('BEGIN'); await client.query(`UPDATE rizenicpartsmaster SET part_main_no=$1, part_no=$2, part_name=$3, car_model=$4, part_category=$5, unit_price=$6 WHERE part_id=$7;`, [part_main_no || null, part_no, part_name, car_model || null, part_category, parseFloat(unit_price) || 0.00, req.params.id]); await client.query(`INSERT INTO rizenic_part_locations (part_no, branch_name, location, safety_stock) VALUES ($1, $2, $3, $4) ON CONFLICT (part_no, branch_name) DO UPDATE SET location = $3, safety_stock = $4;`, [part_no, branch, location || null, parseInt(safety_stock) || 0]); await client.query('COMMIT'); res.json({ success: true }); } catch (e) { await client.query('ROLLBACK'); res.status(500).json({ error: e.message }); } finally { client.release(); } });
router.delete('/parts/:id', async (req, res) => { try { await pool.query('DELETE FROM rizenicpartsmaster WHERE part_id = $1', [req.params.id]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });

router.get('/part-orders', async (req, res) => { try { res.json((await pool.query('SELECT * FROM rizenic_part_orders ORDER BY order_id DESC')).rows); } catch (e) { res.status(500).json({ error: e.message }); } });
router.post('/part-orders', async (req, res) => { try { const d = req.body; const result = await pool.query(`INSERT INTO rizenic_part_orders (qt_no, so_no, epc_no, order_date, est_arrival_date, car_plate, vin_no, car_model, part_main_no, part_no, part_name, qty_ordered, qty_received, order_status, part_type, branch_name, notes, job_id, received_date) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 0, $13, $14, $15, $16, $17, $18) RETURNING *;`, [d.qt_no || null, d.so_no || null, d.epc_no || null, d.order_date, d.est_arrival_date || null, d.car_plate || null, d.vin_no || null, d.car_model || null, d.part_main_no || null, d.part_no, d.part_name, parseInt(d.qty_ordered) || 1, d.order_status || 'รอสั่งซื้อ', d.part_type || 'อะไหล่แท้', d.branch_name, d.notes || null, d.job_id || null, d.received_date || null]); res.status(201).json({ success: true, data: result.rows[0] }); } catch (e) { res.status(500).json({ error: e.message }); } });
router.put('/part-orders/:id', async (req, res) => { try { const d = req.body; await pool.query(`UPDATE rizenic_part_orders SET part_no=COALESCE($1, part_no), part_main_no=$2, part_name=COALESCE($3, part_name), qty_ordered=COALESCE($4, qty_ordered), epc_no=$5, order_status=COALESCE($6, order_status), est_arrival_date=$7, received_date=$8, qt_no=COALESCE($9, qt_no), so_no=COALESCE($10, so_no), order_date=COALESCE($11, order_date), car_plate=COALESCE($12, car_plate), vin_no=COALESCE($13, vin_no), car_model=COALESCE($14, car_model), part_type=COALESCE($15, part_type), notes=$16, job_id=COALESCE($17, job_id) WHERE order_id=$18`, [d.part_no || null, d.part_main_no || null, d.part_name || null, d.qty_ordered || null, d.epc_no || null, d.order_status || null, d.est_arrival_date || null, d.received_date || null, d.qt_no || null, d.so_no || null, d.order_date || null, d.car_plate || null, d.vin_no || null, d.car_model || null, d.part_type || null, d.notes || null, d.job_id || null, req.params.id]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });
router.put('/part-orders/:id/fast', async (req, res) => { try { const { field, value } = req.body; const validFields = ['epc_no', 'part_no', 'part_main_no', 'part_name', 'qty_ordered', 'order_status', 'est_arrival_date', 'received_date', 'notes', 'car_plate', 'qt_no', 'so_no']; if (!validFields.includes(field)) return res.status(400).json({ error: 'ไม่อนุญาตให้แก้ฟิลด์นี้' }); await pool.query(`UPDATE rizenic_part_orders SET ${field} = $1 WHERE order_id = $2`, [value === '' ? null : value, req.params.id]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });
router.delete('/part-orders/:id', async (req, res) => { try { await pool.query('DELETE FROM rizenic_part_orders WHERE order_id = $1', [req.params.id]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });

router.post('/part-inbound', async (req, res) => { try { const d = req.body; const inputQty = parseInt(d.qty) || 1; await pool.query(`INSERT INTO rizenic_part_inbound (received_date, epc_no, part_main_no, part_no, part_name, car_model, qty, unit_price, branch_name) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`, [d.received_date, d.epc_no || null, d.part_main_no || null, d.part_no, d.part_name, d.car_model || null, inputQty, parseFloat(d.unit_price) || 0.00, d.branch_name || 'สำนักงานใหญ่']); if (d.epc_no && d.part_no) { const orderCheck = await pool.query(`SELECT order_id, qty_ordered, COALESCE(qty_received, 0) as current_rcv FROM rizenic_part_orders WHERE epc_no = $1 AND part_no = $2 LIMIT 1`, [d.epc_no, d.part_no]); if (orderCheck.rows.length > 0) { const order = orderCheck.rows[0]; const newQtyReceived = parseInt(order.current_rcv) + inputQty; let newStatus = newQtyReceived >= parseInt(order.qty_ordered) ? 'อะไหล่มาครบแล้ว' : 'อะไหล่ยังมาไม่ครบ'; await pool.query(`UPDATE rizenic_part_orders SET qty_received = $1, order_status = $2, received_date = $3 WHERE order_id = $4`, [newQtyReceived, newStatus, d.received_date, order.order_id]); } } res.status(201).json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });
router.get('/part-inbound', async (req, res) => { try { res.json((await pool.query('SELECT * FROM rizenic_part_inbound ORDER BY inbound_id DESC')).rows); } catch (e) { res.status(500).json({ error: e.message }); } });
router.put('/part-inbound/:id/fast', async (req, res) => { try { const { field, value } = req.body; const validFields = ['received_date', 'qty', 'unit_price', 'epc_no', 'part_no', 'part_main_no', 'part_name']; if (!validFields.includes(field)) return res.status(400).json({ error: 'ไม่อนุญาต' }); await pool.query(`UPDATE rizenic_part_inbound SET ${field} = $1 WHERE inbound_id = $2`, [value || null, req.params.id]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });
router.delete('/part-inbound/:id', async (req, res) => { try { await pool.query('DELETE FROM rizenic_part_inbound WHERE inbound_id=$1', [req.params.id]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });

router.post('/part-outbound', async (req, res) => { try { const d = req.body; await pool.query(`INSERT INTO rizenic_part_outbound (issue_date, part_no, part_main_no, part_name, qty, car_plate, qt_no, so_no, unit_price, part_type, car_model, job_status, branch_name) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)`, [d.issue_date, d.part_no, d.part_main_no || null, d.part_name, parseInt(d.qty) || 1, d.car_plate, d.qt_no || null, d.so_no || null, parseFloat(d.unit_price) || 0.00, d.part_type || null, d.car_model || null, d.job_status || null, d.branch_name || 'สำนักงานใหญ่']); res.status(201).json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });
router.get('/part-outbound', async (req, res) => { try { res.json((await pool.query('SELECT * FROM rizenic_part_outbound ORDER BY outbound_id DESC')).rows); } catch (e) { res.status(500).json({ error: e.message }); } });
router.put('/part-outbound/:id', async (req, res) => { try { const d = req.body; await pool.query(`UPDATE rizenic_part_outbound SET issue_date=$1, part_no=$2, part_name=$3, qty=$4, car_plate=$5, qt_no=$6, so_no=$7, job_status=$8 WHERE outbound_id=$9`, [d.issue_date, d.part_no, d.part_name, parseInt(d.qty), d.car_plate, d.qt_no, d.so_no, d.job_status, req.params.id]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });
router.put('/part-outbound/:id/fast', async (req, res) => { try { const { field, value } = req.body; const validFields = ['issue_date', 'qty', 'job_status', 'part_no', 'part_main_no', 'part_name', 'car_plate', 'qt_no', 'so_no']; if (!validFields.includes(field)) return res.status(400).json({ error: 'ไม่อนุญาต' }); await pool.query(`UPDATE rizenic_part_outbound SET ${field} = $1 WHERE outbound_id = $2`, [value || null, req.params.id]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });
router.delete('/part-outbound/:id', async (req, res) => { try { await pool.query('DELETE FROM rizenic_part_outbound WHERE outbound_id=$1', [req.params.id]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } });

router.get('/parts-inventory', async (req, res) => { try { const branch = req.query.branch; if (!branch) return res.status(400).json({ error: 'ระบุสาขา' }); const result = await pool.query(`SELECT i.part_main_no, i.part_no, i.part_name, i.car_model, COALESCE(SUM(i.qty), 0) AS total_inbound, COALESCE(MAX(o.total_issued), 0) AS total_issued, COALESCE(MAX(o.total_booked), 0) AS total_booked FROM rizenic_part_inbound i LEFT JOIN (SELECT part_no, branch_name, SUM(CASE WHEN COALESCE(job_status, '') != 'รอเข้าซ่อม' THEN qty ELSE 0 END) AS total_issued, SUM(CASE WHEN job_status = 'รอเข้าซ่อม' THEN qty ELSE 0 END) AS total_booked FROM rizenic_part_outbound WHERE branch_name = $1 GROUP BY part_no, branch_name) o ON i.part_no = o.part_no AND i.branch_name = o.branch_name WHERE i.branch_name = $1 GROUP BY i.part_main_no, i.part_no, i.part_name, i.car_model, i.branch_name ORDER BY i.part_name ASC;`, [branch]); res.json(result.rows); } catch (e) { res.status(500).json({ error: e.message }); } });

module.exports = router;