package com.rizenic.backend.parts;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonAlias;
import java.math.BigDecimal; import java.time.LocalDate;
public final class PartsDtos { private PartsDtos(){}
 public record Part(Long id,@JsonProperty("part_id") Long partId,@JsonProperty("part_no") String partNo,@JsonProperty("part_main_no") String mainPartNo,@JsonProperty("part_name") String name,@JsonProperty("part_category") String category,String unit,@JsonProperty("unit_price") BigDecimal defaultPrice,@JsonProperty("location") String location,@JsonProperty("safety_stock") BigDecimal safetyStock,@JsonProperty("car_model") String carModel,boolean active,@JsonProperty("compatible_with_all_models") boolean compatibleAll){ public Part(Long id,String no,String main,String name,String category,String unit,BigDecimal price,boolean active,boolean all){this(id,id,no,main,name,category,unit,price,null,null,null,active,all);} }
 public record PartRequest(@JsonProperty("part_no") String partNo,@JsonProperty("part_main_no") String mainPartNo,@JsonProperty("part_name") String name,@JsonProperty("part_category") @JsonAlias("category") String category,String unit,@JsonProperty("unit_price") @JsonAlias("default_unit_price") BigDecimal defaultPrice,@JsonProperty("compatible_with_all_models") Boolean compatibleAll){}
 public record PartStatus(Long id,@JsonProperty("status_id") Long statusId,String code,@JsonProperty("status_name") String name,boolean active){public PartStatus(Long id,String code,String name,boolean active){this(id,id,code,name,active);}}
 public record StatusRequest(String code,@JsonProperty("status_name") String name){}
 public record Order(Long id,@JsonProperty("order_id") Long legacyId,@JsonProperty("branch_name") String branchName,@JsonProperty("epc_no") String epcNo,@JsonProperty("order_date") LocalDate orderDate,String notes,ListItem[] items){}
 public record ListItem(Long id,@JsonProperty("part_no") String partNo,@JsonProperty("part_main_no") String mainPartNo,@JsonProperty("part_name") String partName,@JsonProperty("qty_ordered") BigDecimal quantity,@JsonProperty("qty_received") BigDecimal quantityReceived,@JsonProperty("job_id") Long jobId,@JsonProperty("order_status") String status,@JsonProperty("car_plate") String carPlate,@JsonProperty("car_model") String carModel,@JsonProperty("vin_no") String vin,@JsonProperty("qt_no") String qtNo,@JsonProperty("so_no") String soNo,@JsonProperty("est_arrival_date") LocalDate estimatedArrival,@JsonProperty("received_date") LocalDate receivedDate){}
 public record OrderRequest(@JsonProperty("branch_name") String branchName,@JsonProperty("epc_no") String epcNo,@JsonProperty("order_date") LocalDate orderDate,String notes,ListItemRequest[] items,@JsonProperty("part_no") String partNo,@JsonProperty("part_name") String partName,@JsonProperty("qty_ordered") BigDecimal quantity,@JsonProperty("job_id") Long jobId,@JsonProperty("order_status") String status){}
 public record ListItemRequest(@JsonProperty("part_no") String partNo,@JsonProperty("part_name") String partName,@JsonProperty("qty_ordered") BigDecimal quantity,@JsonProperty("job_id") Long jobId,@JsonProperty("order_status") String status,@JsonProperty("part_type") String partType){}
 public record Receipt(Long id,@JsonProperty("inbound_id") Long legacyId,@JsonProperty("branch_name") String branchName,@JsonProperty("received_date") LocalDate receivedDate,ListItem[] items){}
 public record ReceiptRequest(@JsonProperty("branch_name") String branchName,@JsonProperty("received_date") LocalDate receivedDate,@JsonProperty("epc_no") String epcNo,@JsonProperty("part_no") String partNo,@JsonProperty("part_name") String partName,BigDecimal qty,@JsonProperty("unit_price") BigDecimal unitPrice){}
 public record Outbound(Long id,@JsonProperty("outbound_id") Long legacyId,@JsonProperty("branch_name") String branchName,@JsonProperty("issue_date") LocalDate issueDate,@JsonProperty("part_no") String partNo,@JsonProperty("part_main_no") String mainPartNo,@JsonProperty("part_name") String partName,BigDecimal qty,@JsonProperty("job_status") String jobStatus,@JsonProperty("car_plate") String carPlate,@JsonProperty("qt_no") String qtNo,@JsonProperty("so_no") String soNo){public Outbound(Long id,Long legacy,String branch,LocalDate date,String no,String name,BigDecimal qty,String status){this(id,legacy,branch,date,no,null,name,qty,status,null,null,null);}}
 public record OutboundRequest(@JsonProperty("branch_name") String branchName,@JsonProperty("issue_date") LocalDate issueDate,@JsonProperty("part_no") String partNo,@JsonProperty("part_name") String partName,BigDecimal qty,@JsonProperty("job_id") Long jobId,@JsonProperty("job_status") String jobStatus,@JsonProperty("unit_price") BigDecimal unitPrice){}
 public record Inventory(@JsonProperty("part_main_no") String mainPartNo,@JsonProperty("part_no") String partNo,@JsonProperty("part_name") String partName,@JsonProperty("car_model") String carModel,@JsonProperty("total_inbound") BigDecimal inbound,@JsonProperty("total_issued") BigDecimal issued,@JsonProperty("total_booked") BigDecimal booked,@JsonProperty("quantity_on_hand") BigDecimal onHand,@JsonProperty("quantity_reserved") BigDecimal reserved,@JsonProperty("quantity_available") BigDecimal available){}
}
