-- Compatibility schema inferred from Database.zip and app.js, NOT original production DDL.
-- No guessed foreign keys: the export contains unmatched legacy references.
-- Empty SQL exports are omitted because their schemas are unknown and app.js does not use them.
BEGIN;
CREATE SCHEMA rizenic_old;
SET LOCAL search_path TO rizenic_old;
ALTER DATABASE rizenic_db SET search_path TO rizenic_old;

CREATE TABLE "customers" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_name" text,
    "phone_number" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "inspection_reports" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "job_id" text,
    "car_plate" text,
    "branch_name" text,
    "fuel_level" integer DEFAULT 0,
    "current_mileage" numeric DEFAULT 0,
    "job_type" text,
    "job_category" text,
    "repair_checklist" jsonb DEFAULT '{}'::jsonb,
    "inventory_checklist" jsonb DEFAULT '{}'::jsonb,
    "electrical_checklist" jsonb DEFAULT '{}'::jsonb,
    "car_diagram_image" text,
    "fuel_gauge_image" text,
    "customer_signature" text,
    "inspector_signature" text,
    "customer_signature_delivery" text,
    "inspector_signature_delivery" text,
    "notes" text,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "claim_no" text
);

CREATE TABLE "rizeniccarmodelmaster" (
    "model_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "car_brand" text,
    "car_model" text
);

CREATE TABLE "rizeniccustomertypemaster" (
    "customer_type_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type_code" text,
    "type_name" text
);

CREATE TABLE "rizenicemployeemaster" (
    "employee_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_code" text,
    "employee_name" text,
    "employee_role" text,
    "employee_phone" text,
    "is_active" boolean DEFAULT true,
    "branch_name" text,
    "username" text,
    "password" text,
    "accessible_pages" text
);

CREATE TABLE "rizenicinsurancemaster" (
    "insurance_code" text PRIMARY KEY,
    "insurance_name" text,
    "insurance_type" text
);

CREATE TABLE "rizenicpartsmaster" (
    "part_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "part_main_no" text,
    "part_no" text,
    "part_name" text,
    "car_model" text,
    "part_category" text,
    "unit_price" numeric DEFAULT 0,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (part_no)
);

CREATE TABLE "rizenicreport" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "contact_date" date,
    "appointment_date" date,
    "customer_type" text,
    "customer_name" text,
    "phone_number" text,
    "car_plate" text,
    "car_brand" text,
    "car_model" text,
    "vin_no" text,
    "payment_type" text,
    "sa_owner" text,
    "damage_level" text,
    "main_part_name" text,
    "main_part_qty" integer DEFAULT 0,
    "sub_part_name" text,
    "sub_part_qty" integer DEFAULT 0,
    "cost_labor" numeric DEFAULT 0,
    "cost_part" numeric DEFAULT 0,
    "cost_external" numeric DEFAULT 0,
    "job_status" text,
    "expected_finish_date" date,
    "actual_finish_date" date,
    "delivery_date" date,
    "quotation_no" text,
    "job_order_no" text,
    "ivn_no" text,
    "notes" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "target_finish_date" date,
    "customer_phone" text,
    "branch_name" text,
    "arrived_date" date,
    "station_kho" boolean DEFAULT false,
    "station_pou" boolean DEFAULT false,
    "station_puan" boolean DEFAULT false,
    "station_pon" boolean DEFAULT false,
    "station_prak" boolean DEFAULT false,
    "station_kat" boolean DEFAULT false,
    "station_qc" boolean DEFAULT false,
    "station_mag" boolean DEFAULT false,
    "station_kraj" boolean DEFAULT false,
    "station_film" boolean DEFAULT false,
    "station_pak" boolean DEFAULT false,
    "station_ready" boolean DEFAULT false,
    "repair_notes" text,
    "repair_finish_date" date,
    "qt_no" text,
    "so_no" text,
    "bl_no" text,
    "epc_no" text,
    "part_status" text,
    "order_part_date" date,
    "est_part_date" date,
    "ordered_part_names" text,
    "department_routing" text,
    "insurance_pay_date" date,
    "is_parked" text,
    "billing_date" date,
    "car_color" text,
    "claim_no" text,
    "complain_note" text
);

CREATE TABLE "rizenicstatusmaster" (
    "status_code" text PRIMARY KEY,
    "status_name" text,
    "department" text,
    "route_page" text
);

CREATE TABLE "rizenic_body_parts" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "part_name" text,
    "category" text
);

CREATE TABLE "rizenic_part_inbound" (
    "inbound_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "received_date" date,
    "epc_no" text,
    "part_no" text,
    "part_main_no" text,
    "part_name" text,
    "car_model" text,
    "qty" integer DEFAULT 0,
    "unit_price" numeric DEFAULT 0,
    "branch_name" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "rizenic_part_locations" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "part_no" text,
    "branch_name" text,
    "location" text,
    "safety_stock" integer DEFAULT 0,
    UNIQUE (part_no, branch_name)
);

CREATE TABLE "rizenic_part_orders" (
    "order_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "qt_no" text,
    "so_no" text,
    "epc_no" text,
    "order_date" date,
    "est_arrival_date" date,
    "received_date" date,
    "order_time" text,
    "car_plate" text,
    "vin_no" text,
    "car_model" text,
    "part_no" text,
    "part_main_no" text,
    "qty_ordered" integer DEFAULT 0,
    "qty_received" integer DEFAULT 0,
    "order_status" text,
    "part_name" text,
    "part_type" text,
    "branch_name" text,
    "notes" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "report_id" integer,
    "job_id" integer
);

CREATE TABLE "rizenic_part_outbound" (
    "outbound_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "issue_date" date,
    "part_no" text,
    "part_main_no" text,
    "part_name" text,
    "qty" integer DEFAULT 0,
    "car_plate" text,
    "qt_no" text,
    "so_no" text,
    "unit_price" numeric DEFAULT 0,
    "part_type" text,
    "car_model" text,
    "job_status" text,
    "branch_name" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "job_id" integer
);

CREATE TABLE "rizenic_part_status_master" (
    "status_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "status_name" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "rizenic_quotas" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "quota_type" text,
    "quota_date" date,
    "branch_name" text,
    "quota_arrived" integer DEFAULT 0,
    "quota_target" integer DEFAULT 0,
    "quota_delivery" integer DEFAULT 0,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "quota_color_parts" integer DEFAULT 0,
    "quota_main_parts" integer DEFAULT 0,
    "quota_sub_parts" integer DEFAULT 0
);

CREATE TABLE "rizenic_routing_master" (
    "routing_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "routing_name" text
);

CREATE TABLE "user_column_preferences" (
    "user_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "emp_name" text,
    "hidden_columns" jsonb DEFAULT '{}'::jsonb,
    "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "row_highlights" jsonb DEFAULT '{}'::jsonb,
    UNIQUE (emp_name)
);

-- Indexes for lookups already performed by the legacy application.
CREATE INDEX ON rizenicreport (branch_name, arrived_date);
CREATE INDEX ON rizenicreport (car_plate, contact_date);
CREATE INDEX ON rizenicemployeemaster (username);
CREATE INDEX ON rizenic_part_orders (job_id);
CREATE INDEX ON rizenic_part_orders (report_id);
CREATE INDEX ON rizenic_part_orders (epc_no, part_no);
CREATE INDEX ON rizenic_part_inbound (branch_name, part_no);
CREATE INDEX ON rizenic_part_outbound (branch_name, part_no);
CREATE INDEX ON inspection_reports (job_id, id DESC);
CREATE INDEX ON rizenic_quotas (branch_name, quota_type, quota_date);

COMMIT;
